-- Tabla para rate limiting de login (brute force protection)
create table if not exists login_attempts (
  id bigint generated by default as identity primary key,
  ip text not null,
  created_at timestamptz not null default now()
);

-- Índice para consultas rápidas por IP + ventana de tiempo
create index if not exists idx_login_attempts_ip_time on login_attempts (ip, created_at desc);

-- Política RLS: solo service_role puede leer/escribir (no expuesta a clientes)
alter table login_attempts enable row level security;

create policy "Login attempts solo service_role"
  on login_attempts for all
  using (auth.role() = 'service_role');

-- Función para limpiar intentos viejos (>24h)
create or replace function clean_old_login_attempts()
returns void
language plpgsql
security definer
as $$
begin
  delete from login_attempts
  where created_at < now() - interval '24 hours';
end;
$$;
